# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('code', models.CharField(max_length=1000)),
                ('submission_time', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('C', 'Compilation Error'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('RE', 'Runtime Error'), ('TLE', 'Time Limit Exceed')], max_length=1)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JudgeSystem.Problem')),
            ],
        ),
    ]
