# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 16:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('JudgeSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('problem_list', models.ManyToManyField(to='JudgeSystem.Problem')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.AddField(
            model_name='solution',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='solved',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='verdict',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='solution',
            name='solver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JudgeSystem.JudgeUser'),
        ),
    ]
