# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JudgeSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
