# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JudgeSystem', '0002_auto_20160422_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.CharField(max_length=4000),
        ),
    ]
