# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JudgeSystem', '0002_auto_20160121_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeuser',
            name='contrib_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='setter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JudgeSystem.JudgeUser'),
        ),
    ]
