# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JudgeSystem', '0003_auto_20160121_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgeuser',
            name='problem_list',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='solver',
        ),
        migrations.AddField(
            model_name='judgeuser',
            name='solution_list',
            field=models.ManyToManyField(to='JudgeSystem.Solution'),
        ),
    ]
