# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JudgeSystem', '0005_auto_20160225_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeuser',
            name='AC_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='judgeuser',
            name='RE_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='judgeuser',
            name='TLE_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='judgeuser',
            name='WA_Count',
            field=models.IntegerField(default=0),
        ),
    ]
