# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JudgeSystem', '0006_auto_20160320_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeuser',
            name='CE_Count',
            field=models.IntegerField(default=0),
        ),
    ]
