# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JudgeSystem', '0007_judgeuser_ce_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeuser',
            name='AC_Count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='judgeuser',
            name='CE_Count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='judgeuser',
            name='RE_Count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='judgeuser',
            name='TLE_Count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='judgeuser',
            name='WA_Count',
            field=models.IntegerField(default=1),
        ),
    ]
