# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JudgeSystem', '0008_auto_20160320_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField()),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbyUser', to='JudgeSystem.JudgeUser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentbyUser', to='JudgeSystem.JudgeUser')),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentOnBlog', to='JudgeSystem.BlogPost')),
            ],
        ),
    ]
