# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JudgeSystem', '0010_auto_20160329_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
