# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JudgeSystem', '0011_auto_20160329_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='comments',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommentsOnProblem', to='JudgeSystem.BlogPost'),
        ),
    ]
